name: 'jaffle_shop_external'
version: '1.0.0'
config-version: 2

profile: default

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"


seeds:
  jaffle_shop_external:
    +persist_docs:
      relation: true
      columns: true
    autre:
      +schema: dbt_raw_autre
      +tags: 'autre'

    raw:
      +schema: seeds_raw
      +tags: 'learn'
      # The post-hooks of these seeds create the final tables in dbt_raw_jaffle_shop and dbt_raw_stripe

# grants for postgreSQL
on-run-end:
  - "{% do grant_select(schema='dbt_raw_autre', role='lecteur') %}
     {% do grant_select(schema='dbt_raw_jaffle_shop', role='lecteur') %}
     {% do grant_select(schema='dbt_raw_stripe', role='lecteur') %}"

flags:
  require_unique_project_resource_names: true

