name: 'jaffle_shop_external'
version: '1.0.0'
config-version: 2

profile: 'default'

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"


seeds:
  jaffle_shop_external:
    +persist_docs:
      relation: true
      columns: true
    autre:
      +schema: dbt_raw_autre
      +tags: 'autre'
      # The post_hook of these seeds defines the reader grants on the schema
    raw:
      +schema: seeds_raw
      +tags: 'learn'
      # The post-hooks of these seeds create the final tables in dbt_raw_jaffle_shop and dbt_raw_stripe
      # and define the reader grants on both schemas
      
      # Do not create dependencies between these seeds and models anywhere else
      # Otherwise, compilation may crash due to transaction handling if these seeds are disabled
      # https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook#transaction-behavior
      # These seeds are only used to prepare the source tables for the Jaffle tutorial (hence the separate project)
      # dbt seed --full-refresh --profile pg       (for PostgreSql)
      # dbt seed --full-refresh --profile default  (for BigQuery)

flags:
  require_unique_project_resource_names: true

