name: 'jaffle_shop_external'
version: '1.0.0'
config-version: 2

profile: 'default'

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"


on-run-end:
  - "{% if target.type == 'postgres' %}grant usage on schema {{ target.schema }} to lecteur;{% endif %}"
  - "{% if target.type == 'postgres' and env_var('DBT_ENV_NAME', 'sans') == 'dev' %}grant usage on schema seeds_autre to lecteur;{% endif %}"
  - "{% if target.type == 'postgres' and env_var('DBT_ENV_NAME', 'sans') == 'dev' %}grant usage on schema seeds_raw to lecteur;{% endif %}"


seeds:
  jaffle_shop_external:
    +persist_docs:
      relation: true
      columns: true
    autre:
      +schema: seeds_autre
      +tags: 'autre'
    raw:
      +schema: seeds_raw
      +tags: 'raw'
      # Ces seeds ne doivent être actifs que pour charger les tables definitives
      # Le post_hook de ces seeds créée les tables definitives
      # La compilation plante a cause de la gestion de la transaction
      # https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook#transaction-behavior
      # dbt seed --select raw --full-refresh --vars '{"load_source_data": "True"}'  [--profile pg]
      # +enabled: "{{ var('load_source_data', 'False') | as_bool }}"



flags:
  require_unique_project_resource_names: true
